name: "dbt_hiive"
version: "1.0.0"
config-version: 2


profile: "dbt_hiive"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_hiive:  # Replace with your project name
    marts:
      +materialized: table  # Default materialization for marts is table
    sources:
      +materialized: view   # Default materialization for sources is view
    base:
      +materialized: view   # Default materialization for base is view
    staging:
      +materialized: view   # Optionally, set staging models as views
