version: 2

models:
  - name: fct_hiive__transaction_transitions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: opened_at
        tests:
          - not_null
      - name:
